### ISSUE TITLE
how to getUpdates?

### ISSUE THREAD

**Issue by dcsan** [benjick/meteor-telegram-bot#2]
thanks for wrapping this up...

your example shows how to poll for slash commands, but how do i receive all text, esp via long polling?
- i've set the bot privacy mode to disabled 
- I tried using an empty string as the command but no works

ref
https://core.telegram.org/bots/api#getupdates

**Comment by dcsan** [comment]
also the slash commands don't seem to return a chatID, so i cant identify a chat to send a message to, unless its replying to an incoming message.

**Comment by dcsan** [comment]
ok i see you're calling `method("getUpdates"`  internally

https://github.com/benjick/meteor-telegram-bot/blob/master/telegram-bot.js#L19

and you have something setup for a catchAll

```
    if(msg = item.message.text) {
            msg = TelegramBot.parseCommandString(msg)
            var obj = _.find(TelegramBot.triggers, function(obj) { return obj.command == msg[0] })
            if(obj) {
                TelegramBot.send(obj.callback(msg, from, item.message), chatId)
            }
        }
        else {
            if(typeof(TelegramBot.catchAll) === 'function') {
                TelegramBot.catchAll(item);
            }
        }
```

but it looks like the catchAll won't run for just the case where there's no command found - it will only run if     `if(msg = item.message.text) {` evals to false.

so there's no way to just listen for a command _with_ a message.text?

**Comment by benjick** [comment]
Hey

I guess catchAll should be named as catchOthers, because it's catching everything that's not a text message. It's kinda shitty implemented right now so I wouldn't use it

**Comment by benjick** [comment]
Removed the use of catchAll in the latest version
