### ISSUE TITLE
telegram contact list

### ISSUE THREAD

**Issue by 1z2x3cc4** [benjick/meteor-telegram-bot#21]
Hi
I'm developing an app that uses telegram to sign in people and then I want to get their contact list from telegram and add their friends to my app ....

I wanted to know is it possible to get contact list using this package or I have to write an API ?

**Comment by benjick** [comment]
This is for the bot api only

**Comment by shrmnk** [comment]
Unfortunately, that would mean that no, it is not possible to get the contact list with this package. You would have to directly talk to the [Telegram API](https://core.telegram.org/)
