### ISSUE TITLE
Menu(Keyboard) creation Example

### ISSUE THREAD

**Issue by babnik63** [benjick/meteor-telegram-bot#7]
Dear friend.
Is it possible to show us some code about menu creation?
I think this project needs more sample codes.

Thanks.

**Comment by benjick** [comment]
Hi sorry for the long reply. I can look into it later today if you still need it

**Comment by mojtabaeslami** [comment]
Hi 
It doesn't work.
would you please send me test code.

**Comment by elie222** [comment]
Here's a simple example:

```
      TelegramBot.method('sendMessage', {
        chat_id: conversationId,
        text: 'Please choose an option:',
        reply_markup: JSON.stringify({
          keyboard: [
             ["xx"],
             ["yy"]
           ]
        })
      });
```

Or try `inline_keyboard` instead of `keyboard`.

**Comment by shrmnk** [comment]
#26
